name: Helios actions

on: 
pull_request:
push:
branches:
-master
-develop

jobs: 
build:
name: Runing Intergration Tests

runs-on: ubuntu-latest


steps:
-uses:actions/checkout@v1
-name: Node.js ${(matrix.node-version)}
uses:actions/setup-node@v1
with:
node-version:${(matrix.node-version)}
- name:npm install, build, and test
run: |
npm ci
npm build --if-present
npm test
env:
CI: true
